### ISSUE TITLE
Fatal Exception: java.lang.NullPointerException

### ISSUE THREAD

**Issue by Another1dd** [adaptyteam/AdaptySDK-Android#10]
Fatal Exception: java.lang.NullPointerException
Attempt to invoke virtual method 'java.lang.String org.json.JSONObject.optString(java.lang.String)' on a null object reference

com.android.billingclient.api.SkuDetails.getType (SkuDetails.java:1)
com.adapty.internal.AdaptyInternal.makePurchase (AdaptyInternal.java:168)
com.adapty.Adapty.makePurchase (Adapty.java:120)
com.adapty.Adapty.makePurchase$default (Adapty.java:111)

Device: HUAWEI nova 5T, android 10

**Comment by vladd-g** [comment]
@Another1dd it's a very strange crash from the Billing Library itself, and I don't see any other causes but an obfuscation issue, since we don't pass any arguments that could break anything, it's just a no-arg getter, and the NPE occurs inside SkuDetails itself.

Do you have `-keep class com.android.billingclient.** { *; }` in your proguard config?

**Comment by Another1dd** [comment]
I will try to add -keep class com.android.billingclient.** { *; }. We have only one crash in crashlytics with this problem.
